### PR TITLE
Add MCS On-Call checklist

### PR DESCRIPTION
**Pull request by StevenBarre**

### CODE REVIEW

**Review by wmhutchison — APPROVED** [review]
👍

**Comment by tbaker1313** [comment]
If there something weird about this file? If you preview it, you get an error in line 1 column 1 ?

**Comment by StevenBarre** [comment]
> If there something weird about this file? If you preview it, you get an error: Error in user YAML: (): did not find expected key while parsing a block mapping at line 1 column 1

No, the preview tool is just treating the file as Yaml, when its a mix of yaml and markdown. https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms#markdown-issue-template

**Review by DanDeane — APPROVED** [review]
I approve !

**Pull request merged**
